'use client';

import Link from 'next/link';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

export default function Home() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-blue-50 to-white">
      {/* Hero Section */}
      <div className="container mx-auto px-4 py-16">
        <div className="text-center mb-16">
          <h1 className="text-5xl font-bold mb-4 text-gray-900">
            AI Travel Planner
          </h1>
          <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
            Plan your perfect trip with AI-powered itinerary generation. Get personalized recommendations, budget estimates, and hotel suggestions.
          </p>
          <div className="flex gap-4 justify-center">
            <Link href="/register">
              <Button size="lg" className="text-lg">
                Get Started
              </Button>
            </Link>
            <Link href="/login">
              <Button size="lg" variant="outline" className="text-lg">
                Login
              </Button>
            </Link>
          </div>
        </div>

        {/* Features */}
        <div className="grid md:grid-cols-3 gap-8 mt-20">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                🤖 AI-Powered Planning
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Get intelligent, personalized travel itineraries generated by advanced AI based on your preferences and budget.
              </CardDescription>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                💰 Budget Management
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Receive detailed budget breakdowns including flights, accommodation, food, and activities tailored to your spending level.
              </CardDescription>
            </CardContent>
          </Card>

          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                ✏️ Editable Itineraries
              </CardTitle>
            </CardHeader>
            <CardContent>
              <CardDescription>
                Customize your trip by adding, removing, or regenerating activities. Make your itinerary truly yours.
              </CardDescription>
            </CardContent>
          </Card>
        </div>

        {/* How It Works */}
        <div className="mt-20 text-center">
          <h2 className="text-3xl font-bold mb-12">How It Works</h2>
          <div className="grid md:grid-cols-4 gap-6">
            <div>
              <div className="w-12 h-12 bg-blue-500 text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                1
              </div>
              <h3 className="font-semibold mb-2">Enter Details</h3>
              <p className="text-gray-600 text-sm">
                Provide destination, duration, budget, and interests
              </p>
            </div>
            <div>
              <div className="w-12 h-12 bg-blue-500 text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                2
              </div>
              <h3 className="font-semibold mb-2">AI Generation</h3>
              <p className="text-gray-600 text-sm">
                Our AI creates a personalized itinerary for you
              </p>
            </div>
            <div>
              <div className="w-12 h-12 bg-blue-500 text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                3
              </div>
              <h3 className="font-semibold mb-2">Customize</h3>
              <p className="text-gray-600 text-sm">
                Edit activities and regenerate days as needed
              </p>
            </div>
            <div>
              <div className="w-12 h-12 bg-blue-500 text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                4
              </div>
              <h3 className="font-semibold mb-2">Travel!</h3>
              <p className="text-gray-600 text-sm">
                Enjoy your perfectly planned adventure
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Footer */}
      <footer className="bg-gray-100 mt-20 py-8">
        <div className="container mx-auto px-4 text-center text-gray-600">
          <p>&copy; 2026 AI Travel Planner. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}
